// Photography shown in the reel, the film strip and the lightbox.
// To add a photo: drop the full image in photos/ (about 1800px on the long edge),
// a smaller copy in photos/thumbs/ (about 760px), then add an entry below.
// Entries appear in this order.
window.PHOTOS = [
  {
    src: "photos/chinatown-10th-street.jpg",
    thumb: "photos/thumbs/chinatown-10th-street.jpg",
    width: 1500,
    height: 1013,
    caption: "10th Street",
    place: "Chinatown, Philadelphia",
    alt: "A busy corner on 10th Street in Philadelphia's Chinatown, with bunting strung over the street and people crossing",
  },
  {
    src: "photos/crowd-surf.jpg",
    thumb: "photos/thumbs/crowd-surf.jpg",
    width: 1500,
    height: 1013,
    caption: "Crowd surf",
    place: "",
    alt: "A smiling crowd surfer carried on raised hands at a packed show, with a painted mural behind the band",
  },
  {
    src: "photos/friendship-gate.jpg",
    thumb: "photos/thumbs/friendship-gate.jpg",
    width: 1500,
    height: 1013,
    caption: "Friendship Gate",
    place: "Chinatown, Philadelphia",
    alt: "The Chinatown Friendship Gate on 10th Street, with American flags and America 250 banners strung across the intersection",
  },
  {
    src: "photos/the-crew.jpg",
    thumb: "photos/thumbs/the-crew.jpg",
    width: 1500,
    height: 1013,
    caption: "The crew",
    place: "",
    alt: "A group of friends crowded together at a party under flash, grinning and pointing at the camera",
  },
  {
    src: "photos/golden-hour.jpg",
    thumb: "photos/thumbs/golden-hour.jpg",
    width: 1800,
    height: 1216,
    caption: "Golden hour",
    place: "",
    alt: "Late sun pouring over wild grasses on a rooftop, with the city skyline and a brick building glowing behind",
  },
  {
    src: "photos/bowl-show.jpg",
    thumb: "photos/thumbs/bowl-show.jpg",
    width: 1292,
    height: 1086,
    caption: "Bowl show",
    place: "",
    alt: "Looking down into a skate bowl packed with people at a show, fans sitting along the red coping above the crowd",
  },
  {
    src: "photos/chinatown-afternoon.jpg",
    thumb: "photos/thumbs/chinatown-afternoon.jpg",
    width: 1800,
    height: 1216,
    caption: "Chinatown afternoon",
    place: "Chinatown, Philadelphia",
    alt: "A red-haired guy with a backpack looking down a sunny Chinatown street lined with red lampposts and strings of flags",
  },
  {
    src: "photos/behind-the-decks.jpg",
    thumb: "photos/thumbs/behind-the-decks.jpg",
    width: 1800,
    height: 1216,
    caption: "Behind the decks",
    place: "",
    alt: "Three people at a DJ booth under flash, one pointing at the camera with headphones around his neck",
  },
  {
    src: "photos/afternoon-flare.jpg",
    thumb: "photos/thumbs/afternoon-flare.jpg",
    width: 1800,
    height: 1216,
    caption: "Afternoon flare",
    place: "Center City, Philadelphia",
    alt: "The sun flaring between Center City towers, with a Philadelphia banner on a lamppost below",
  },
  {
    src: "photos/live-set.jpg",
    thumb: "photos/thumbs/live-set.jpg",
    width: 1500,
    height: 1013,
    caption: "Live set",
    place: "",
    alt: "A crowd packed in front of a band playing under warm lights, with a painted mural on the wall behind them",
  },
  {
    src: "photos/one-way.jpg",
    thumb: "photos/thumbs/one-way.jpg",
    width: 1358,
    height: 907,
    caption: "One Way",
    place: "Philadelphia",
    alt: "A bent One Way sign glowing against a hazy sky beside a sunlit office tower",
  },
  {
    src: "photos/mixing.jpg",
    thumb: "photos/thumbs/mixing.jpg",
    width: 1800,
    height: 1216,
    caption: "Mixing",
    place: "",
    alt: "A DJ in orange headphones working a white controller while people lean on the booth behind the laptop",
  },
  {
    src: "photos/chinatown-banner.jpg",
    thumb: "photos/thumbs/chinatown-banner.jpg",
    width: 1800,
    height: 1216,
    caption: "家",
    place: "Chinatown, Philadelphia",
    alt: "A red Chinatown banner with the character 家 on a lamppost, under strings of America 250 flags",
  },
];
